config/routes.rb
Sample::Application.routes.draw do
  resources :performances
  
  resources :projects

  resources :platforms

  resources :employees

  devise_for :views

  resources :homes

  devise_for :users, :path_names => { :sign_up => "register" }

  root :to => 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :eamil, :location, :mobile, :name, :platform_id
  belongs_to :platform
  has_many :performances
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  before_filter :authenticate_user!
  def index
    @employees = Employee.order("updated_at DESC").page(params[:page]).per(5)
    
        respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="index">
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "domain" %><br />
    <%= f.select :platform_id, Platform.all.map{|p| [p.platform,p.id]} %>
  </div>
  <div class="field">
    <%= f.label :eamil %><br />
    <%= f.text_field :eamil %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
  </div>
 
<% end %>

app/views/employees/edit.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>Editing employee</marquee>

<%= render 'form' %>
</div>
<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>Listing employees</marquee>
  
  
  <table border="0" cellspacing="1" cellpadding="1" class="stipe">
    <tr>
      <th>Name</th>
      <th>Platform</th>
      <th>Eamil</th>
      <th>Location</th>
      <th>Mobile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    
  <% @employees.each do |employee| %>
      <tr>
      <td><%= employee.name %></td>
      <td><%= employee.platform.platform %></td>
      <td><%= employee.eamil %></td>
      <td><%= employee.location %></td>
      <td><%= employee.mobile %></td>
      <td><%= link_to 'Show', employee %></td>
      <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
    <% end %>
  </table>

  <br />
  
  <%= paginate @employees %>
  
</div> 
 
<%= render :partial => "/share/right_side"%>

</div>

app/views/employees/new.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>New employee</marquee>

<%= render 'form' %>
</div>
</div>

app/views/employees/show.html.erb
<div class="index">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Platform:</b>
  <%= @employee.platform.platform %>
</p>

<p>
  <b>Eamil:</b>
  <%= @employee.eamil %>
</p>

<p>
  <b>Location:</b>
  <%= @employee.location %>
</p>

<p>
  <b>Mobile:</b>
  <%= @employee.mobile %>
</p>

</div>

<%= link_to 'Edit', edit_employee_path(@employee) %> 
<%= link_to 'Back', employees_path %>