config/routes.rb
Sample::Application.routes.draw do
  resources :performances
  
  resources :projects

  resources :platforms

  resources :employees

  devise_for :views

  resources :homes

  devise_for :users, :path_names => { :sign_up => "register" }

  root :to => 'employees#index'

end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @platforms }
    end
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
    @platform = Platform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/new
  # GET /platforms/new.json
  def new
    @platform = Platform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/1/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(params[:platform])

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render json: @platform, status: :created, location: @platform }
      else
        format.html { render action: "new" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /platforms/1
  # PUT /platforms/1.json
  def update
    @platform = Platform.find(params[:id])

    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<div class="index">
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :platform %><br />
    <%= f.text_field :platform %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>Editing platform</marquee>

<%= render 'form' %>
</div>
<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>
</div>

app/views/platforms/index.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>Listing platforms</marquee>

<table border="0" cellspacing="0" cellpadding="0" class="stipe">
  <tr>
    <th>Platform</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @platforms.each do |platform| %>
  <tr>
    <td><%= platform.platform %></td>
    <td><%= link_to 'Show', platform %></td>
    <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
    <td><%= link_to 'Destroy', platform, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= paginate @platforms %>
</div>

<%= render :partial => "/share/right_side"%>
</div>

app/views/platforms/new.html.erb
<div class="indexcontainer">
<div class="index">
<marquee>New platform</marquee>

<%= render 'form' %>
</div>
<%= link_to 'Back', platforms_path %>
</div>

app/views/platforms/show.html.erb
<div class="index">
<p id="notice"><%= notice %></p>

<p>
  <b>Platform:</b>
  <%= @platform.platform %>
</p>

</div>
<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>